/*Paso 4: Generar bandera Delay*/
CREATE TABLE RAW.NW3 AS
SELECT * ,
CASE WHEN DELAY <= 0  THEN 'A:SIN RETRASO'
      WHEN DELAY > 0 AND DELAY <= 10 THEN 'B:RETRASO_MENOR10'
	  WHEN DELAY > 10 AND DELAY <= 20 THEN 'C:RETRASO_MENOR20'
	  WHEN DELAY > 20 AND DELAY <= 30 THEN 'C:RETRASO_MENOR30'
	  WHEN DELAY > 30 AND DELAY <= 40 THEN 'C:RETRASO_MENOR40'
	  WHEN DELAY > 40 AND DELAY <= 50 THEN 'C:RETRASO_MENOR50'
	  WHEN DELAY > 50 AND DELAY <= 60 THEN 'C:RETRASO_MENOR60'
      ELSE 'H:RETRASO_MAYOR60'
END AS BANDERA_DELAY
FROM RAW.NW2
;
