/*Paso 12: Pegar la tabla de Maximos a la tabla del rank*/
DROP TABLE IF EXISTS TRANSFORM.NW10;
CREATE TABLE TRANSFORM.NW10 AS
SELECT t1.*, t2.MAX
FROM TRANSFORM.NW9 t1
INNER JOIN TRANSFORM.MAX_NW t2
ON (t1.ID_AVION = t2.ID_AVION AND t1.FECHA = t2.FECHA)
ORDER BY t1.ID_AVION, t1.FECHA, t1.HORASALIDAF
;
