/*Paso 15: Generar el Lag con el ind_retraso2*/
DROP TABLE IF EXISTS TRANSFORM.NW13;
CREATE TABLE TRANSFORM.NW13 AS
SELECT *,
	LAG(IND_RETRASO1 ,1) OVER (
		ORDER BY ID_AVION, FECHA, HORASALIDAF
	) IND_RETRASO2
FROM TRANSFORM.NW12
;
