/*Paso 30: Regresar a la tabla original de todo los vuelos de NW*/
CREATE TABLE RAW.NW28 AS
SELECT t1.*, t2.SUM_EFECTOS_DOMINO, t2.TOT_SUM_DOMINO, t2.COUNT3 AS VUELOS_AFECTADOS
FROM RAW.NW15 t1
LEFT JOIN RAW.NW27 t2
ON (t1.FECHA = t2.FECHA AND t1.ID_AVION = t2.ID_AVION AND t1.RANK_CONTADOR = t2.RANK_CONTADOR)
ORDER BY ID_AVION, FECHA, HORASALIDAF;
;







