/*Paso 21: SUMA_EFECTOS Se suma la variable EFECTOS_DOMINO y se agrupa por Id_avion y Fecha*/
CREATE TABLE RAW.NW19 AS
SELECT FECHA, ID_AVION, (SUM(EFECTOS_DOMINO)) AS SUM_EFECTOS_DOMINO
FROM RAW.NW18
GROUP BY FECHA, ID_AVION
;