/*Paso 10: Realizar el conteo de vuelos por Fecha y Id_vuelo*/
DROP TABLE IF EXISTS TRANSFORM.NW9;
CREATE TABLE TRANSFORM.NW9 AS
SELECT *,
	RANK() OVER (
			PARTITION BY ID_AVION, FECHA
			ORDER BY ID_AVION, FECHA, HORASALIDAF) rank_contador
FROM TRANSFORM.NW8
;
