/*Paso 14: Se empieza a generar el efecto domino*/
/*Generar bandera de los afectados*/
DROP TABLE IF EXISTS TRANSFORM.NW12;
CREATE TABLE TRANSFORM.NW12 AS
SELECT *, CASE WHEN BANDERA_DELAY = 'A:SIN RETRASO' THEN 0 ELSE 1 END AS IND_RETRASO1
FROM TRANSFORM.NW11
;
