/*Paso 20: Encontrar el vuelo que genera el efecto domino*/
DROP TABLE IF EXISTS TRANSFORM.NW18;
CREATE TABLE TRANSFORM.NW18 AS
SELECT *, CASE WHEN EFECTO = 'DOMINO' AND EFECTO2 = 'SIN EFECTO'
THEN 1 ELSE 0 END AS EFECTOS_DOMINO
FROM TRANSFORM.NW17
;
