/*Paso 19: Generar el Lag con la bandera de efecto*/
DROP TABLE IF EXISTS TRANSFORM.NW17;
CREATE TABLE TRANSFORM.NW17 AS
SELECT *,
	LAG(EFECTO ,1) OVER (
		ORDER BY ID_AVION, FECHA, HORASALIDAF
	) EFECTO2
FROM TRANSFORM.NW16
;
