/*Paso 26: Modificar los negativos*/
DROP TABLE IF EXISTS TRANSFORM.NW24;
CREATE TABLE TRANSFORM.NW24 AS
SELECT *,
CASE WHEN TOT_SUM_DOMINO < 0 THEN 0 ELSE TOT_SUM_DOMINO END AS TOT_SUM_DOMINO2
FROM TRANSFORM.NW23
;
