/*Paso 4: Generar bandera Delay2*/
DROP TABLE IF EXISTS TRANSFORM.NW3;
CREATE TABLE TRANSFORM.NW3 AS
SELECT * ,
CASE WHEN DELAY2 = 0  THEN 'A:SIN RETRASO'
      WHEN DELAY2 > 0 AND DELAY2 <= 10 THEN 'B:RETRASO_MENOR10'
	  WHEN DELAY2 > 10 AND DELAY2 <= 20 THEN 'C:RETRASO_MENOR20'
	  WHEN DELAY2 > 20 AND DELAY2 <= 30 THEN 'C:RETRASO_MENOR30'
	  WHEN DELAY2 > 30 AND DELAY2 <= 40 THEN 'C:RETRASO_MENOR40'
	  WHEN DELAY2 > 40 AND DELAY2 <= 50 THEN 'C:RETRASO_MENOR50'
	  WHEN DELAY2 > 50 AND DELAY2 <= 60 THEN 'C:RETRASO_MENOR60'
      ELSE 'H:RETRASO_MAYOR60'
END AS BANDERA_DELAY
FROM TRANSFORM.NW2_5
;