/*Paso 23: Eliminar cuando ocurren dobles o triples efectos domino*/
DROP TABLE IF EXISTS TRANSFORM.NW21;
CREATE TABLE TRANSFORM.NW21 AS
SELECT *
FROM TRANSFORM.NW20
WHERE SUM_EFECTOS_DOMINO <= 1
ORDER BY ID_AVION, FECHA, HORASALIDAF
;
