/*Paso 9: Ordenar esta tabla por Id_avion, Hora de salidaF y Fecha */
DROP TABLE IF EXISTS TRANSFORM.NW8;
CREATE TABLE TRANSFORM.NW8 AS
SELECT *
FROM TRANSFORM.NW7
WHERE DELAY IS NOT NULL
ORDER BY ID_AVION, FECHA, HORASALIDAF
;
