/*Paso 24: Total efectos domino*/
DROP TABLE IF EXISTS TRANSFORM.NW22;
CREATE TABLE TRANSFORM.NW22 AS
SELECT ID_AVION, FECHA, (SUM(SUM_EFECTOS_DOMINO)-1) AS TOT_SUM_DOMINO
FROM TRANSFORM.NW21
GROUP BY ID_AVION, FECHA
;
