/* Paso 2: Modificar nombres de columnas*/
CREATE TABLE RAW.NW2 AS
SELECT YEAR, MONTH AS MES, DAY_OF_MONTH AS DIA_MES, DAY_OF_WEEK AS DIA_SEMANA,
OP_UNIQUE_CARRIER AS ID_OPERADOR, TAIL_NUM AS ID_AVION, OP_CARRIER_FL_NUM AS NUM_VUELO,
ORIGIN AS ORIGEN, DEST AS DESTINO, CRS_DEP_TIME AS HORASALIDAF, DEP_TIME AS SALIDA_REALF,
DEP_DELAY AS DELAY, CRS_ARR_TIME AS HORA_LLEGADA_PROGF, CRS_ELAPSED_TIME AS TIEMPO_TRANS_VUELO,
DISTANCE AS DISTANCIA_MILLAS
FROM RAW.NW
;
