/*Paso 25: Regresar a la tabla NW23 pegando el total*/
DROP TABLE IF EXISTS TRANSFORM.NW23;
CREATE TABLE TRANSFORM.NW23 AS
SELECT t1.*, t2.TOT_SUM_DOMINO
FROM TRANSFORM.NW21 t1
LEFT JOIN TRANSFORM.NW22 t2
ON (t1.FECHA = t2.FECHA AND t1.ID_AVION = t2.ID_AVION)
;
