/*Paso 17: Crear el efecto domino igualando IND1 vs IND3*/
DROP TABLE IF EXISTS TRANSFORM.NW15;
CREATE TABLE TRANSFORM.NW15 AS
SELECT *, CASE WHEN IND_RETRASO1 = IND_RETRASO3 AND IND_RETRASO1 = 1
THEN 'DOMINO' ELSE 'SIN EFECTO' END AS EFECTO
FROM TRANSFORM.NW14 t1
;
