/*Paso 27: Count_inverso1*/
DROP TABLE IF EXISTS TRANSFORM.NW25;
CREATE TABLE TRANSFORM.NW25 AS
SELECT *,
	-1+RANK() OVER (
			PARTITION BY ID_AVION, FECHA
			ORDER BY ID_AVION, FECHA, HORASALIDAF) rank_contador2
FROM TRANSFORM.NW24
;
