/*Paso 5: Crear la fecha de vuelo*/
DROP TABLE IF EXISTS TRANSFORM.NW4;
CREATE TABLE TRANSFORM.NW4 AS
SELECT * ,
CASE WHEN DIA_MES = '1' OR DIA_MES = '2' OR DIA_MES = '3' OR DIA_MES = '4' OR DIA_MES = '5'
	OR DIA_MES = '6' OR DIA_MES = '7' OR DIA_MES = '8' OR DIA_MES = '9' THEN CONCAT('0',DIA_MES)
	ELSE DIA_MES END AS DAY,
CASE WHEN MES = '1' OR MES = '2' OR MES = '3' OR MES = '4' OR MES = '5' OR MES = '6'
	OR MES = '7' OR MES = '8' OR MES = '9' THEN CONCAT('0',MES) ELSE MES END AS MONTH,
CASE WHEN DIA_SEMANA = '1' THEN 'A:LUNES'
	WHEN DIA_SEMANA = '2' THEN 'B:MARTES'
	WHEN DIA_SEMANA = '3' THEN 'C:MIERCOLES'
	WHEN DIA_SEMANA = '4' THEN 'D:JUEVES'
	WHEN DIA_SEMANA = '5' THEN 'E:VIERNES'
	WHEN DIA_SEMANA = '6' THEN 'F:SABADO'
	WHEN DIA_SEMANA = '7' THEN 'G:DOMINGO'
	ELSE DIA_SEMANA END AS DAY_SEM
FROM TRANSFORM.NW3
;
