/*Paso 11: Tomar el maximo rank por Fecha y Id_Vuelo*/
DROP TABLE IF EXISTS TRANSFORM.MAX_NW;
CREATE TABLE TRANSFORM.MAX_NW AS
SELECT (MAX(rank_contador)) AS MAX,
       ID_AVION, FECHA
FROM TRANSFORM.NW9
GROUP BY ID_AVION, FECHA
ORDER BY ID_AVION, FECHA
;
